#!/bin/bash  
# vim: fdm=marker:fdl=0
# update submodules {{{
yadm submodule update --recursive --init
# }}} 
# install function definitions {{{
function install_key {
    gpg -k $key 2>&1 > /dev/null || gpg --recv-key $key
}
# }}}
# restore packages from list {{{
restorepkgs $HOME/.yadm/packages.txt
# }}}
# shell: zsh {{{
[ $SHELL = "/usr/bin/zsh" ] || su -c "usermod -s /usr/bin/zsh $USER"
# }}}
# vim {{{
sudo pip2.7 install neovim
sudo pip install neovim
# }}}
# systemd {{{
sudo systemctl enable org.cups.cupsd.service
sudo systemctl enable cups-browsed.service
sudo systemctl enable avahi-daemon.service
# network
sudo sytemctl enable bluetooth.service

# bitwarden
sudo cp $HOME/.yadm/delete-bwhash-on-exit.service /etc/systemd/system/delete-bwhash-on-exit.service
sudo systemctl daemon-reload
sudo systemctl enable delete-bwhash-on-exit.service
# }}}
# automatic keyring unlock {{{
cat /etc/pam.d/login | grep pam_gnome_keyring.so > /dev/null || 
    echo "For automated keyring unlocking upon login, follow instructions (regarding PAM) at https://wiki.archlinux.org/index.php/GNOME/Keyring#Using_the_keyring_outside_GNOME"
# }}}
# set up {{{
# {{{ misc
merge-rofi
sudo cp $HOME/.config/lightdm-slick-greeter/slick-greeter.conf /etc/lightdm/slick-greeter.conf
# }}}
# node without sudo {{{
mkdir .node
echo "prefix = ~/.node" > .npmrc
npm install ionic cordova
# }}}
# {{{ oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
# }}}
# {{{ vim-plug
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# }}}
# symlinks {{{ 
sh $HOME/.yadm/create-symlinks
#}}}
# }}}
echo bootstrapping done
